### criar horario
POST http://localhost:3000/horarios/normal
Content-Type: application/json

{ "dia_semana": "Segunda-feira", "hora_inicio": "09:00", "hora_fim": "17:00", "profissional_id": 1 }

### buscar horarios por profissional
GET http://localhost:3000/horarios/normal/1

### buscar horarios bloqueados por profissional
GET http://localhost:3000/horarios/bloqueado/1

### bloquear horario
POST http://localhost:3000/horarios/bloqueado
Content-Type: application/json

{ "profissional_id": 1, "inicio": "2026-07-06 12:00:00", "fim": "2026-07-06 13:00:00", "motivo": "Consulta médica" }

### buscar horarios bloqueados por profissional
GET http://localhost:3000/horarios/disponivel/1?data=2026-07-06